### ISSUE TITLE
Failed to compile on Win7-64 with Rust 1.38

### ISSUE THREAD

**Issue by mark-summerfield** [ohadravid/wmi-rs#15]
I would really love to use your wmi module. Unfortunately though, it won't build for me:
```
R:\rs\wmitest>cargo run --release --
   Compiling wmi v0.4.5
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> C:\Users\mark\.cargo\registry\src\github.com-1ecc6299db9ec823\wmi-0.4.5\src\lib.rs:101:1
    |
101 | #![feature(ptr_internals, custom_attribute)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `wmi`.

To learn more, run the command again with --verbose.
R:\rs\wmitest>rustc -V
rustc 1.38.0 (625451e37 2019-09-23)
```

**Comment by mark-summerfield** [comment]
Thank you. I copied the example from the front of the github page and it compiled and ran fine.
However, it issued many warnings. I suppressed these by adding two lines:

```rust
    // added the next two lines to suppress warnings
    #[allow(non_camel_case_types)]
    #[allow(non_snake_case)]
    #[derive(Deserialize, Debug)]
    struct Win32_OperatingSystem {
        Caption: String,
    // etc.
```

**Comment by ohadravid** [comment]
You are totally right, I updated the README to suppress the warnings (via the module-level attributes similar to what you wrote)
